### ISSUE TITLE
Heal improvement

### ISSUE THREAD

**Issue by minijaham** [DavidFlashCZ/HealAndFeed#1]
Change $sender->setHealth(20) to $sender->setHealth($sender->getMaxHealth())
So that way, it’s compatible with CustomEnchantments plugin

**Comment by DavidFlashCZ** [comment]
Thank you for your suggestion! I will not be working on this plugin no more tho, because this all will be moved to my newest plugin called FlashCore! There will be /hub, /vanish, /fly, /feed and /heal, /freeze and much more! You can send suggestions to FlashCore plugin.

**Comment by minijaham** [comment]
xD okay! I'll be looking forward to it :)
